# Generated by Django 4.0.4 on 2022-04-28 04:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Время окончания (необязательно)', null=True, validators=[django.core.validators.MinValueValidator(models.DateTimeField(help_text='Время начала', verbose_name='Начинается в'))], verbose_name='Заканчивается в'),
        ),
    ]
