# Generated by Django 4.0.4 on 2022-05-03 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(blank=True, help_text='+7(000)000-00-00 или +7(0000)000-00-00', max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Номер телефона ожидается в формате +7(000)000-00-00', regex='^\\+7(\\d{3,4}?)\\d{3}?-\\d{2}?-\\d{2}?$')], verbose_name='Номер телефона'),
        ),
    ]
