# Generated by Django 4.0.4 on 2022-05-03 07:55

import accounts.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to=accounts.models.user.User.user_directory_path, verbose_name='Изображение пользователя'),
        ),
    ]
