# Generated by Django 4.0.4 on 2022-05-03 13:20

import accounts.models.user
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='std/nophoto400.jpg', upload_to=accounts.models.user.User.user_directory_path, verbose_name='Изображение пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(blank=True, help_text='+7(000)000-00-00 или +7(0000)000-00-00', max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Номер телефона ожидается в формате +7(000)000-00-00', regex='^\\+7\\(\\d{3,4}\\)\\d{3}(?:-\\d{2}){2}$')], verbose_name='Номер телефона'),
        ),
    ]
