# Generated by Django 4.0.4 on 2022-04-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='Время начала', verbose_name='Начинается в')),
                ('end_time', models.DateTimeField(blank=True, help_text='Время окончания (необязательно)', null=True, verbose_name='Заканчивается в')),
                ('notes', models.TextField(blank=True, help_text='Максимум 1000 символов  (необязательно)', max_length=1000, verbose_name='Примечание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Наименование конференции', max_length=255, unique=True, verbose_name='Конференция')),
                ('con_reference', models.CharField(blank=True, default='Ссылка для подключения пока не указана', help_text='Адрес для подкючения к конференции', max_length=255, verbose_name='Ссылка на конференцию')),
                ('con_pass', models.CharField(blank=True, default='Не требуется', help_text='Пароль для входа (Необязательно). Не более 255 символов.', max_length=255, verbose_name='Пароль для входа в конференцию')),
            ],
            options={
                'verbose_name': 'Конференция',
                'verbose_name_plural': 'Конференции',
            },
        ),
    ]
