# Generated by Django 4.0.4 on 2022-04-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование события', max_length=255, verbose_name='Event Name')),
                ('day', models.DateField(help_text='Дата события', verbose_name='Event Date')),
                ('start_time', models.TimeField(help_text='Время начала', verbose_name='Start Time')),
                ('end_time', models.TimeField(help_text='Время окончания', verbose_name='End Time')),
                ('notes', models.TextField(help_text='Примечание', verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
