# Generated by Django 4.0.4 on 2022-04-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_conference_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Время окончания (необязательно)', null=True, verbose_name='Заканчивается в'),
        ),
    ]
