# Generated by Django 4.0.4 on 2022-04-26 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_conf', to='events.conference', verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rel_roles', to='participants.participantrole', verbose_name='Роль участника'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
