# Generated by Django 4.0.4 on 2022-04-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participantrole',
            options={'verbose_name': 'Роль в конференции', 'verbose_name_plural': 'Роли в конференции'},
        ),
        migrations.AlterField(
            model_name='participantrole',
            name='role',
            field=models.CharField(default='Посетитель', max_length=255, unique=True, verbose_name='Роль'),
        ),
    ]
